### PR TITLE
Add command "--conv-cfg" to convert config formats

### PR DESCRIPTION
**Pull request by bneuen**
Added new command "--conv-cfg" to convert config formats.  This
uses --load FILE to specify the input filename and --save FILE
to specify the output filename.  These must come after the
--conv-cfg command, or a bad input error will be occur.

### CODE REVIEW

**Comment by bneuen** [comment]
Did the bootloader.c issue get resolved?

**Comment by mgong98** [comment]
Flashing issue still a problem with your pull request.
The merge should have been only the the accd93b commit.
Looks like all commits were merged instead.

**Comment by mgong98** [comment]
Please add new pull request with 1 commit per pull request.  
commit 5dc7d78 for conv-fw with changes to bootloader.c has an issue.
Other comments were okay, but cherry-picking did not work for some reason and all commits were merged instead.  Reverted commits for now.

**Comment by bneuen** [comment]
I find it hard to believe that 5dc7d78 would cause an issue in framing, as that change should be quite isolated in the functionality it touches.  The more likely culprit would be 2333173.  Are you sure it isn't that one?

**Comment by mgong98** [comment]
Yes, I was mistaken.  It is the 2333173.

**Comment by bneuen** [comment]
I had trouble reproducing the issue.  I captured the frame output using a .enc I had available before and after these changes, and they were exactly the same.  Can you send me the .enc that expressed the issue?

**Comment by mgong98** [comment]
Issue was not related to the conv-fw command usage, but in the --flash usage which uses the same code that was modified in the pull request.

Command: mxt-app --flash mXT2952T2_0x03_2.3.AA.enc --verbose 4  (outputs following failure)

.
.
.
Bootloader Found
Sending frames ...
Frame 1: size 12366
Frame too big

Frames should be much smaller such as 128.

**Comment by bneuen** [comment]
Yeah, I was using the --flash argument, though in a simulation mode I added (which basically just bypasses checks for the mxt chip, see: https://github.com/bneuen/mxt-app/commit/ad9a2edac637d86a8ac8128cbcfb8b50ac487b76).  Like I said, the frame output before and after was the same.  That is why I would like the .enc that actually presents the issue.  Also, what platform are you running it on?  Is it x86_64 (that is what I was running on)?

**Pull request merged**
