### PR TITLE
Fix AOSP build again

### PR DESCRIPTION
**Pull request by bneuen**
Fix faulty commit 5f6821917fa948a535299324c6c58129be910a9e

### CODE REVIEW

**Comment by mgong98** [comment]
Tested and merged

**Comment by bneuen** [comment]
Sorry, I did not mean for the "Allow removing USB from AOSP build" commit to get in this pull request, but it was ready.

**Comment by mgong98** [comment]
That is fine.  It worked fine.  I will update the Readme at a later point to clarify usage.

**Comment by bneuen** [comment]
That change did update the readme.  You can see if more explanation is needed, but maybe it is sufficient?

**Comment by mgong98** [comment]
Thanks.  Didn't notice it at first.

**Pull request merged**
